[package]
name = "rustnitrogen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
reqwest = "0.12.3"
termcolor = "1.4.1"
winapi = "0.3.9"
